--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1.pgdg120+1)
-- Dumped by pg_dump version 17.5 (Debian 17.5-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: vehicle; Type: TABLE; Schema: public; Owner: quarkus
--

CREATE TABLE public.vehicle (
    acceleration double precision NOT NULL,
    braking double precision NOT NULL,
    handling double precision NOT NULL,
    is_special_vehicle boolean,
    price numeric(38,2) NOT NULL,
    release_date date,
    seats integer NOT NULL,
    top_speed double precision NOT NULL,
    id bigint NOT NULL,
    manufacturer character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    vehicle_class character varying(255) NOT NULL
);


ALTER TABLE public.vehicle OWNER TO quarkus;

--
-- Name: vehicle_id_seq; Type: SEQUENCE; Schema: public; Owner: quarkus
--

ALTER TABLE public.vehicle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicle_modifications; Type: TABLE; Schema: public; Owner: quarkus
--

CREATE TABLE public.vehicle_modifications (
    vehicle_id bigint NOT NULL,
    modifications character varying(255)
);


ALTER TABLE public.vehicle_modifications OWNER TO quarkus;

--
-- Name: vehicle_seq; Type: SEQUENCE; Schema: public; Owner: quarkus
--

CREATE SEQUENCE public.vehicle_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.vehicle_seq OWNER TO quarkus;

--
-- Data for Name: vehicle; Type: TABLE DATA; Schema: public; Owner: quarkus
--

COPY public.vehicle (acceleration, braking, handling, is_special_vehicle, price, release_date, seats, top_speed, id, manufacturer, name, vehicle_class) FROM stdin;
8.7	8.5	8.2	f	1000000.00	2013-10-01	2	226	1	Truffade	Adder	Super
9.3	9	9.2	f	725000.00	2014-05-13	2	230	2	Pegassi	Zentorno	Super
9.5	9.3	9.4	f	2200000.00	2015-07-08	2	232	3	Progen	T20	Super
9.1	9	9.1	f	1950000.00	2015-06-10	2	230	4	Pegassi	Osiris	Super
9.6	9.2	9.5	f	2700000.00	2016-06-21	2	235	5	Grotti	X80 Proto	Super
9.8	9.4	9.8	f	1535000.00	2017-07-25	2	238	6	Dewbauchee	Vagner	Super
9.7	9.5	9.7	f	2875000.00	2019-08-08	2	233	7	Benefactor	Krieger	Super
8.5	8.3	9	f	95000.00	2013-10-01	2	219	8	Annis	Elegy RH8	Sports
8.7	8.5	8.8	f	240000.00	2014-03-04	2	220	9	Dinka	Jester	Sports
8.6	8.4	8.9	f	100000.00	2013-10-01	2	218	10	Pfister	Comet	Sports
8.4	8.2	8.5	f	90000.00	2013-10-01	2	217	11	Bravado	Banshee	Sports
8.6	8.4	8.7	f	275000.00	2014-05-13	2	219	12	Dewbauchee	Massacro	Sports
8.3	8.1	8.4	f	95000.00	2015-03-10	4	210	13	Karin	Kuruma	Sports
8.2	8	8.3	t	698250.00	2015-03-10	4	208	14	Karin	Kuruma (Armored)	Sports
8.1	7.8	8	f	35000.00	2013-10-01	2	210	15	Vapid	Dominator	Muscle
8	7.7	7.9	f	32000.00	2013-10-01	2	209	16	Bravado	Gauntlet	Muscle
7.8	7.6	7.7	f	0.00	2013-10-01	2	205	17	Imponte	Phoenix	Muscle
7.9	7.7	7.8	f	15000.00	2013-10-01	2	207	18	Declasse	Sabre Turbo	Muscle
8.1	7.8	7.8	t	665000.00	2015-03-10	2	209	19	Imponte	Duke O'Death	Muscle
7.5	7	7.4	f	90000.00	2013-10-01	4	190	20	Gallivanter	Baller	SUV
7.6	7.1	7.5	f	70000.00	2013-10-01	4	192	21	Benefactor	Dubsta	SUV
7.7	7.2	7.6	f	195000.00	2014-05-13	4	195	22	Enus	Huntley S	SUV
7.4	6.9	7.3	f	35000.00	2013-10-01	8	189	23	Declasse	Granger	SUV
7.5	7.2	7.6	f	55000.00	2013-10-01	4	188	24	Obey	Tailgater	Sedan
7.7	7.4	7.8	f	65000.00	2013-10-01	4	192	25	Benefactor	Schafter	Sedan
7.6	7.3	7.7	f	80000.00	2013-10-01	4	190	26	Ubermacht	Oracle	Sedan
7.8	7.5	7.9	f	254000.00	2015-10-20	4	195	27	Enus	Cognoscenti	Sedan
9	7.5	9	f	15000.00	2013-10-01	2	215	28	Pegassi	Bati 801	Motorcycle
9.1	7.6	8.9	f	82000.00	2014-10-13	2	216	29	Shitzu	Hakuchou	Motorcycle
9.3	7.8	9.2	t	2225000.00	2016-11-08	1	220	30	Nagasaki	Shotaro	Motorcycle
9.2	8	9.5	t	3890250.00	2018-07-31	1	210	31	Pegassi	Oppressor Mk II	Motorcycle
8.3	7	8.5	f	8000.00	2013-10-01	2	190	32	Maibatsu	Sanchez	Off-Road
7	6.5	7	f	3000.00	2013-10-01	2	170	33	Karin	Rebel	Off-Road
7.2	6.7	7.2	f	45000.00	2013-10-01	4	175	34	Vapid	Sandking XL	Off-Road
8	7	8	f	550000.00	2016-06-07	2	185	35	Vapid	Trophy Truck	Off-Road
\.


--
-- Data for Name: vehicle_modifications; Type: TABLE DATA; Schema: public; Owner: quarkus
--

COPY public.vehicle_modifications (vehicle_id, modifications) FROM stdin;
1	Engine Upgrade
1	Turbo
1	Custom Spoiler
1	Custom Wheels
2	Engine Upgrade
2	Turbo
2	Lowered Suspension
2	Sport Brakes
2	Carbon Hood
7	Engine Upgrade
7	Turbo
7	Performance Transmission
7	Race Spoiler
7	Lightweight Carbon Body
14	Armored Plating
14	Bulletproof Tires
14	Engine Upgrade
14	Heavy Duty Transmission
19	Roll Cage
19	Armor Plating
19	Reinforced Bumper
19	Engine Upgrade
28	Nitrous Oxide
28	Custom Headlight Neon
28	Light Tron Circuit Design
28	Performance Engine
29	Missile Launchers
29	Countermeasures
29	Jet Engine
29	Stealth Mode
29	Homing Missiles
\.


--
-- Name: vehicle_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quarkus
--

SELECT pg_catalog.setval('public.vehicle_id_seq', 35, true);


--
-- Name: vehicle_seq; Type: SEQUENCE SET; Schema: public; Owner: quarkus
--

SELECT pg_catalog.setval('public.vehicle_seq', 1, false);


--
-- Name: vehicle vehicle_pkey; Type: CONSTRAINT; Schema: public; Owner: quarkus
--

ALTER TABLE ONLY public.vehicle
    ADD CONSTRAINT vehicle_pkey PRIMARY KEY (id);


--
-- Name: vehicle_modifications fkgwl7cvfavfvk7oq5b6d1c9nv1; Type: FK CONSTRAINT; Schema: public; Owner: quarkus
--

ALTER TABLE ONLY public.vehicle_modifications
    ADD CONSTRAINT fkgwl7cvfavfvk7oq5b6d1c9nv1 FOREIGN KEY (vehicle_id) REFERENCES public.vehicle(id);


--
-- PostgreSQL database dump complete
--

